// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Mbk3zPGrWf2opTbCrMVhLNID3N5oeOk',
    appId: '1:377161014135:android:34c66e3def878fa25f9f72',
    messagingSenderId: '377161014135',
    projectId: 'study-flutter-prep',
    databaseURL: 'https://study-flutter-prep-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-flutter-prep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHMDD_kOav1dv9PRt7rf6-SqAu80lGJ3U',
    appId: '1:377161014135:ios:7e0f118614c633ea5f9f72',
    messagingSenderId: '377161014135',
    projectId: 'study-flutter-prep',
    databaseURL: 'https://study-flutter-prep-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-flutter-prep.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
